par(mfrow=c(2,2))
with(df, plot(FullTimeDate, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(df, plot(FullTimeDate, Voltage, type = "l", xlab="datetime", ylab="Voltage"))
with(df, plot(FullTimeDate, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
lines(df$FullTimeDate, df$Sub_metering_2,type="l", col= "red")
lines(df$FullTimeDate, df$Sub_metering_3,type="l", col= "blue")
legend(c("topright"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty= 1, lwd=2, col = c("black", "red", "blue"))
with(df, plot(FullTimeDate, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power"))
dev.copy(png,"plot4.png",height=480,width=480)
dev.off()
